<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Microsoft.Azure.Networking.Infrastructure.RingMaster.Backend.HelperTypes</RootNamespace>
    <AssemblyName>Microsoft.RingMaster.Backend.HelperTypes</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" />
    <!-- Allowing using the latest C# language features -->
    <PackageReference Include="PolySharp" PrivateAssets="All"/>
  </ItemGroup>

  <Import Project="$(StyleCopProps)" />
</Project>
