<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <RuntimeFrameworkVersion>$(DotNetCoreVersion)</RuntimeFrameworkVersion>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <RootNamespace>Microsoft.Azure.Networking.Infrastructure.RingMaster.RingMasterService</RootNamespace>
    <AssemblyName>Microsoft.RingMaster.RingMasterService</AssemblyName>
    <CoverageDisabled>true</CoverageDisabled>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Cloud.InstrumentationFramework.NetStd" Condition="'$(OSSBUILD)' == ''" />
    <PackageReference Include="Bond.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.ServiceFabric" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Extensions" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="entryPoint.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SRCROOT)\Applications\RingMasterApplication\Utilities\Utilities.csproj" />
    <ProjectReference Include="$(SRCROOT)\Backend\Common\RingMasterBackendCommon.csproj" />
    <ProjectReference Include="$(SRCROOT)\Backend\Core\src\RingMasterBackendCore.csproj" />
    <ProjectReference Include="$(SRCROOT)\Backend\HelperTypes\src\HelperTypes.csproj" />
    <ProjectReference Include="$(SRCROOT)\Backend\Instrumentation\RingMasterBackendInstrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Backend\Native\src\SortedDictExt.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\Common\Common.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\RingMasterCommunicationProtocol\RingMasterCommunicationProtocol.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\ZkprCommunicationProtocol\ZkprCommunicationProtocol.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\Instrumentation\Instrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterClient\src\RingMasterClient.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterCommon\src\RingMasterCommon.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterServer\src\RingMasterServer.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\SecureTransport\src\SecureTransport.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\ZooKeeperServer\src\ZooKeeperServer.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\IfxInstrumentation\IfxInstrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\LogFileEventTracing\LogFileEventTracing.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\ServiceFabric\src\ServiceFabric.csproj" />
    <ProjectReference Include="$(SRCROOT)\Persistence\Common\src\PersistenceCommon.csproj" />
    <ProjectReference Include="$(SRCROOT)\Persistence\InMemory\src\InMemoryPersistence.csproj" />
    <ProjectReference Include="$(SRCROOT)\Persistence\ServiceFabric\src\ServiceFabricPersistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <QCustomInput Include="PackageRoot\ServiceManifest.xml" />
  </ItemGroup>

  <Import Project="$(StyleCopProps)" />
</Project>
