// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DistributedJobControllerProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Microsoft.Vega.DistributedJobControllerProto {

  /// <summary>Holder for reflection information generated from DistributedJobControllerProto.proto</summary>
  public static partial class DistributedJobControllerProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for DistributedJobControllerProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DistributedJobControllerProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNEaXN0cmlidXRlZEpvYkNvbnRyb2xsZXJQcm90by5wcm90bxIsTWljcm9z",
            "b2Z0LlZlZ2EuRGlzdHJpYnV0ZWRKb2JDb250cm9sbGVyUHJvdG8aGURpc3RU",
            "ZXN0Q29tbW9uUHJvdG8ucHJvdG8iVAoRR2V0Sm9iU3RhdGVzUmVwbHkSPwoJ",
            "am9iU3RhdGVzGAEgAygLMiwuTWljcm9zb2Z0LlZlZ2EuRGlzdFRlc3RDb21t",
            "b25Qcm90by5Kb2JTdGF0ZSJQChRHZXRKb2JNZXRyaWNzUmVxdWVzdBISCgpt",
            "ZXRyaWNOYW1lGAEgASgJEhIKCnN0YXJ0SW5kZXgYAiABKAUSEAoIcGFnZVNp",
            "emUYAyABKAUiKAoSR2V0Sm9iTWV0cmljc1JlcGx5EhIKCmpvYk1ldHJpY3MY",
            "ASADKAEiRgohR2V0U2VydmljZUluc3RhbmNlSWRlbnRpdGllc1JlcGx5EiEK",
            "GXNlcnZpY2VJbnN0YW5jZUlkZW50aXRpZXMYASADKAkiaQoPU3RhcnRKb2JS",
            "ZXF1ZXN0EhAKCHNjZW5hcmlvGAEgASgJEkQKCnBhcmFtZXRlcnMYAiADKAsy",
            "MC5NaWNyb3NvZnQuVmVnYS5EaXN0VGVzdENvbW1vblByb3RvLkpvYlBhcmFt",
            "ZXRlcjK4BQobRGlzdHJpYnV0ZWRKb2JDb250cm9sbGVyU3ZjEmoKEENhbmNl",
            "bFJ1bm5pbmdKb2ISKS5NaWNyb3NvZnQuVmVnYS5EaXN0VGVzdENvbW1vblBy",
            "b3RvLkVtcHR5GikuTWljcm9zb2Z0LlZlZ2EuRGlzdFRlc3RDb21tb25Qcm90",
            "by5FbXB0eSIAEnwKDEdldEpvYlN0YXRlcxIpLk1pY3Jvc29mdC5WZWdhLkRp",
            "c3RUZXN0Q29tbW9uUHJvdG8uRW1wdHkaPy5NaWNyb3NvZnQuVmVnYS5EaXN0",
            "cmlidXRlZEpvYkNvbnRyb2xsZXJQcm90by5HZXRKb2JTdGF0ZXNSZXBseSIA",
            "EpcBCg1HZXRKb2JNZXRyaWNzEkIuTWljcm9zb2Z0LlZlZ2EuRGlzdHJpYnV0",
            "ZWRKb2JDb250cm9sbGVyUHJvdG8uR2V0Sm9iTWV0cmljc1JlcXVlc3QaQC5N",
            "aWNyb3NvZnQuVmVnYS5EaXN0cmlidXRlZEpvYkNvbnRyb2xsZXJQcm90by5H",
            "ZXRKb2JNZXRyaWNzUmVwbHkiABKcAQocR2V0U2VydmljZUluc3RhbmNlSWRl",
            "bnRpdGllcxIpLk1pY3Jvc29mdC5WZWdhLkRpc3RUZXN0Q29tbW9uUHJvdG8u",
            "RW1wdHkaTy5NaWNyb3NvZnQuVmVnYS5EaXN0cmlidXRlZEpvYkNvbnRyb2xs",
            "ZXJQcm90by5HZXRTZXJ2aWNlSW5zdGFuY2VJZGVudGl0aWVzUmVwbHkiABJ2",
            "CghTdGFydEpvYhI9Lk1pY3Jvc29mdC5WZWdhLkRpc3RyaWJ1dGVkSm9iQ29u",
            "dHJvbGxlclByb3RvLlN0YXJ0Sm9iUmVxdWVzdBopLk1pY3Jvc29mdC5WZWdh",
            "LkRpc3RUZXN0Q29tbW9uUHJvdG8uRW1wdHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Microsoft.Vega.DistTestCommonProto.DistTestCommonProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Vega.DistributedJobControllerProto.GetJobStatesReply), global::Microsoft.Vega.DistributedJobControllerProto.GetJobStatesReply.Parser, new[]{ "JobStates" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Vega.DistributedJobControllerProto.GetJobMetricsRequest), global::Microsoft.Vega.DistributedJobControllerProto.GetJobMetricsRequest.Parser, new[]{ "MetricName", "StartIndex", "PageSize" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Vega.DistributedJobControllerProto.GetJobMetricsReply), global::Microsoft.Vega.DistributedJobControllerProto.GetJobMetricsReply.Parser, new[]{ "JobMetrics" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Vega.DistributedJobControllerProto.GetServiceInstanceIdentitiesReply), global::Microsoft.Vega.DistributedJobControllerProto.GetServiceInstanceIdentitiesReply.Parser, new[]{ "ServiceInstanceIdentities" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Microsoft.Vega.DistributedJobControllerProto.StartJobRequest), global::Microsoft.Vega.DistributedJobControllerProto.StartJobRequest.Parser, new[]{ "Scenario", "Parameters" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetJobStatesReply : pb::IMessage<GetJobStatesReply> {
    private static readonly pb::MessageParser<GetJobStatesReply> _parser = new pb::MessageParser<GetJobStatesReply>(() => new GetJobStatesReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetJobStatesReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Vega.DistributedJobControllerProto.DistributedJobControllerProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobStatesReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobStatesReply(GetJobStatesReply other) : this() {
      jobStates_ = other.jobStates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobStatesReply Clone() {
      return new GetJobStatesReply(this);
    }

    /// <summary>Field number for the "jobStates" field.</summary>
    public const int JobStatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Microsoft.Vega.DistTestCommonProto.JobState> _repeated_jobStates_codec
        = pb::FieldCodec.ForMessage(10, global::Microsoft.Vega.DistTestCommonProto.JobState.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobState> jobStates_ = new pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobState>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobState> JobStates {
      get { return jobStates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetJobStatesReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetJobStatesReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!jobStates_.Equals(other.jobStates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= jobStates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      jobStates_.WriteTo(output, _repeated_jobStates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += jobStates_.CalculateSize(_repeated_jobStates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetJobStatesReply other) {
      if (other == null) {
        return;
      }
      jobStates_.Add(other.jobStates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            jobStates_.AddEntriesFrom(input, _repeated_jobStates_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetJobMetricsRequest : pb::IMessage<GetJobMetricsRequest> {
    private static readonly pb::MessageParser<GetJobMetricsRequest> _parser = new pb::MessageParser<GetJobMetricsRequest>(() => new GetJobMetricsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetJobMetricsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Vega.DistributedJobControllerProto.DistributedJobControllerProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsRequest(GetJobMetricsRequest other) : this() {
      metricName_ = other.metricName_;
      startIndex_ = other.startIndex_;
      pageSize_ = other.pageSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsRequest Clone() {
      return new GetJobMetricsRequest(this);
    }

    /// <summary>Field number for the "metricName" field.</summary>
    public const int MetricNameFieldNumber = 1;
    private string metricName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MetricName {
      get { return metricName_; }
      set {
        metricName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "startIndex" field.</summary>
    public const int StartIndexFieldNumber = 2;
    private int startIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartIndex {
      get { return startIndex_; }
      set {
        startIndex_ = value;
      }
    }

    /// <summary>Field number for the "pageSize" field.</summary>
    public const int PageSizeFieldNumber = 3;
    private int pageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetJobMetricsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetJobMetricsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MetricName != other.MetricName) return false;
      if (StartIndex != other.StartIndex) return false;
      if (PageSize != other.PageSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MetricName.Length != 0) hash ^= MetricName.GetHashCode();
      if (StartIndex != 0) hash ^= StartIndex.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MetricName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MetricName);
      }
      if (StartIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartIndex);
      }
      if (PageSize != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PageSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MetricName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetricName);
      }
      if (StartIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartIndex);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetJobMetricsRequest other) {
      if (other == null) {
        return;
      }
      if (other.MetricName.Length != 0) {
        MetricName = other.MetricName;
      }
      if (other.StartIndex != 0) {
        StartIndex = other.StartIndex;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MetricName = input.ReadString();
            break;
          }
          case 16: {
            StartIndex = input.ReadInt32();
            break;
          }
          case 24: {
            PageSize = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetJobMetricsReply : pb::IMessage<GetJobMetricsReply> {
    private static readonly pb::MessageParser<GetJobMetricsReply> _parser = new pb::MessageParser<GetJobMetricsReply>(() => new GetJobMetricsReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetJobMetricsReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Vega.DistributedJobControllerProto.DistributedJobControllerProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsReply(GetJobMetricsReply other) : this() {
      jobMetrics_ = other.jobMetrics_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetJobMetricsReply Clone() {
      return new GetJobMetricsReply(this);
    }

    /// <summary>Field number for the "jobMetrics" field.</summary>
    public const int JobMetricsFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_jobMetrics_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> jobMetrics_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> JobMetrics {
      get { return jobMetrics_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetJobMetricsReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetJobMetricsReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!jobMetrics_.Equals(other.jobMetrics_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= jobMetrics_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      jobMetrics_.WriteTo(output, _repeated_jobMetrics_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += jobMetrics_.CalculateSize(_repeated_jobMetrics_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetJobMetricsReply other) {
      if (other == null) {
        return;
      }
      jobMetrics_.Add(other.jobMetrics_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            jobMetrics_.AddEntriesFrom(input, _repeated_jobMetrics_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetServiceInstanceIdentitiesReply : pb::IMessage<GetServiceInstanceIdentitiesReply> {
    private static readonly pb::MessageParser<GetServiceInstanceIdentitiesReply> _parser = new pb::MessageParser<GetServiceInstanceIdentitiesReply>(() => new GetServiceInstanceIdentitiesReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetServiceInstanceIdentitiesReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Vega.DistributedJobControllerProto.DistributedJobControllerProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetServiceInstanceIdentitiesReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetServiceInstanceIdentitiesReply(GetServiceInstanceIdentitiesReply other) : this() {
      serviceInstanceIdentities_ = other.serviceInstanceIdentities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetServiceInstanceIdentitiesReply Clone() {
      return new GetServiceInstanceIdentitiesReply(this);
    }

    /// <summary>Field number for the "serviceInstanceIdentities" field.</summary>
    public const int ServiceInstanceIdentitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_serviceInstanceIdentities_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> serviceInstanceIdentities_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ServiceInstanceIdentities {
      get { return serviceInstanceIdentities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetServiceInstanceIdentitiesReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetServiceInstanceIdentitiesReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!serviceInstanceIdentities_.Equals(other.serviceInstanceIdentities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= serviceInstanceIdentities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      serviceInstanceIdentities_.WriteTo(output, _repeated_serviceInstanceIdentities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += serviceInstanceIdentities_.CalculateSize(_repeated_serviceInstanceIdentities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetServiceInstanceIdentitiesReply other) {
      if (other == null) {
        return;
      }
      serviceInstanceIdentities_.Add(other.serviceInstanceIdentities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            serviceInstanceIdentities_.AddEntriesFrom(input, _repeated_serviceInstanceIdentities_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StartJobRequest : pb::IMessage<StartJobRequest> {
    private static readonly pb::MessageParser<StartJobRequest> _parser = new pb::MessageParser<StartJobRequest>(() => new StartJobRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartJobRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Microsoft.Vega.DistributedJobControllerProto.DistributedJobControllerProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartJobRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartJobRequest(StartJobRequest other) : this() {
      scenario_ = other.scenario_;
      parameters_ = other.parameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartJobRequest Clone() {
      return new StartJobRequest(this);
    }

    /// <summary>Field number for the "scenario" field.</summary>
    public const int ScenarioFieldNumber = 1;
    private string scenario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Scenario {
      get { return scenario_; }
      set {
        scenario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parameters" field.</summary>
    public const int ParametersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Microsoft.Vega.DistTestCommonProto.JobParameter> _repeated_parameters_codec
        = pb::FieldCodec.ForMessage(18, global::Microsoft.Vega.DistTestCommonProto.JobParameter.Parser);
    private readonly pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobParameter> parameters_ = new pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Microsoft.Vega.DistTestCommonProto.JobParameter> Parameters {
      get { return parameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartJobRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartJobRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Scenario != other.Scenario) return false;
      if(!parameters_.Equals(other.parameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Scenario.Length != 0) hash ^= Scenario.GetHashCode();
      hash ^= parameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Scenario.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Scenario);
      }
      parameters_.WriteTo(output, _repeated_parameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Scenario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Scenario);
      }
      size += parameters_.CalculateSize(_repeated_parameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartJobRequest other) {
      if (other == null) {
        return;
      }
      if (other.Scenario.Length != 0) {
        Scenario = other.Scenario;
      }
      parameters_.Add(other.parameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Scenario = input.ReadString();
            break;
          }
          case 18: {
            parameters_.AddEntriesFrom(input, _repeated_parameters_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
