<#
.SYNOPSIS
    Updates RingMasterApplication to a new version, which is generated by incrementing the version. This is used to test
    the upgrade scenario.

.EXAMPLE
    .\CloudUnittests\RunSelfUpgrade.ps1 -verbose
#>
[CmdletBinding()]
param(
    [string] $RingMasterApplicationPackagePath = $null,
    [string] $RingMasterApplicationParametersFile = $null
)

$m_waitForAppReadyTimeOutInMinutes = 60

Function Log($Message)
{
    Write-Output "$([DateTime]::Now) $Message"
}

Function WaitForAppReady
{
    $startTime = Get-Date
    while (((Get-Date) - $startTime).TotalMinutes -lt $m_waitForAppReadyTimeOutInMinutes) {
        Write-Verbose "Wait 60 seconds and get app status..."
        Start-Sleep -Second 60

        $script:rma = Get-ServiceFabricApplication -ApplicationTypeName RingMasterApplication
        $rma
        if ($rma.ApplicationStatus -eq "Ready") {
            Write-Verbose "App is ready"
            break
        }
        else {
            Get-ServiceFabricApplicationHealth -ApplicationName $rma.ApplicationName
        }
    }

    if ($rma.ApplicationStatus -ne "Ready") {
        Log "RingMasterApplication is not ready, waiting started at $startTime"
        throw "RingMasterApplication is not ready"
    }
}

Log "Start RingMasterApplication self upgrade and rollback test"

if ([string]::IsNullOrEmpty($RingMasterApplicationPackagePath)) {
    $RingMasterApplicationPackagePath = Join-Path $PSScriptRoot "..\RingMasterApplication-Pkg\RingMasterApplication"
}

if ([string]::IsNullOrEmpty($RingMasterApplicationParametersFile)) {
    $RingMasterApplicationParametersFile = Join-Path $PSScriptRoot "..\RingMasterApplication-Pkg\Local.xml"
}

# On CloudTest fabric code path may not be added to PATH
$fabricCodePath = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Service Fabric' -Name FabricCodePath).FabricCodePath
if ($env:PATH -split ";" | ? { $_ -eq $fabricCodePath }) {
    Write-Verbose "FabricCodePath is in PATH"
}
else {
    $env:PATH += ";$fabricCodePath"
}

Connect-ServiceFabricCluster

# Ensure a base version of the RingMasterApplication is deployed
$rma = Get-ServiceFabricApplication -ApplicationTypeName RingMasterApplication
if ($rma -eq $null) {
    Log "No RingMasterApplication, deploying the base version"

    & $PSScriptRoot\Deploy-ServiceFabricApplication.ps1 `
        -ApplicationPackagePath $RingMasterApplicationPackagePath `
        -ApplicationParametersFile $RingMasterApplicationParametersFile
}

Log "Wait for app to be ready in $m_waitForAppReadyTimeOutInMinutes minutes"
WaitForAppReady

$baseVersion = $rma.ApplicationTypeVersion
Log "Base version $baseVersion is ready. Wait for 5 mins"
Start-Sleep -Second 300

Log "Incrementing app version ..."
& $PSScriptRoot\Increment-ServiceFabricApplicationManifestVersions.ps1 `
    -AppPackagePath $RingMasterApplicationPackagePath -AppTypeName RingMasterApplication -Force

Log "Starting upgrade to new version ..."
& $PSScriptRoot\Upgrade-ServiceFabricApplication.ps1 `
    -ApplicationPackagePath $RingMasterApplicationPackagePath `
    -ApplicationParametersFile $RingMasterApplicationParametersFile `
    -FailureAction Manual

Log "Wait for app to be ready in $m_waitForAppReadyTimeOutInMinutes minutes"
WaitForAppReady
Log "New version is ready. Wait for 5 mins"
Start-Sleep -Second 300

Log "Rollback to base version $baseVersion via upgrade"

$paramXml = [XML] (Get-Content $RingMasterApplicationParametersFile)
$appParameters = @{}
$paramXml.Application.Parameters.Parameter | % {
    $appParameters[$_.Name] = $_.Value
}

while ($true) {
    try {
        Start-ServiceFabricApplicationUpgrade -Monitored -ApplicationName $rma.ApplicationName `
            -ApplicationTypeVersion $baseVersion `
            -ApplicationParameter $appParameters `
            -HealthCheckStableDurationSec 60 `
            -UpgradeDomainTimeoutSec 1200 `
            -UpgradeTimeout 3000 `
            -FailureAction Manual `
            -ErrorAction Stop

        Log "Upgrade to $baseVersion is started"
        break
    }
    catch {
        Write-Verbose "Exception caught, will retry after 5 seconds : $Error"
        $Error.Clear()
        Start-Sleep -Second 5
    }
}

Log "Wait for app to be ready in $m_waitForAppReadyTimeOutInMinutes minutes"
WaitForAppReady

Log "Base version $baseVersion is ready. Upgrade test is completed."

# vim: textwidth=120:expandtab
