// <copyright file="ApiCoverageCalculatorWorker.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>

namespace ApiCoverageCalculator
{
    using System;
    using System.CodeDom;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.ServiceModel;
    using ApiCoverageCalculator.ApiCoverageCalculateRequestModel;
    using CoverageInfoExtractor.MethodCoverageInfoModel;
    using Microsoft.CSharp;
    using Newtonsoft.Json;

    /// <summary>
    /// API Coverage calculator for a specific dll
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class ApiCoverageCalculatorWorker
    {
        private readonly Stopwatch sw;
        private readonly string resourceFolder;
        private readonly Assembly assembly;
        private readonly string coverageFileName;
        private readonly string dllName;
        private readonly string extractorDirectory;
        private readonly string tempFilePath;
        private readonly HashSet<MethodCoverageInfoKey> coveredMethodInfoKeys;
        private readonly Dictionary<string, WrapperInterface> interfaceWrappers;
        private readonly string extractorName = "CoverageInfoExtractor";

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiCoverageCalculatorWorker"/> class
        /// </summary>
        /// <param name="resourceFolder">Resource folder where dll and it's dependencies locates</param>
        /// <param name="dllName">Assembly dll file name</param>
        /// <param name="coverageFileName">Full path of coverage file generated by VS</param>
        /// <param name="interfaceWrappers">Interface wrappers</param>
        public ApiCoverageCalculatorWorker(string resourceFolder, string dllName, string coverageFileName, Dictionary<string, WrapperInterface> interfaceWrappers)
        {
            this.sw = Stopwatch.StartNew();
            this.resourceFolder = string.IsNullOrEmpty(resourceFolder) ? Directory.GetCurrentDirectory() : resourceFolder;
            this.assembly = !string.IsNullOrEmpty(dllName) ? Assembly.LoadFrom(Path.Combine(resourceFolder, dllName)) : throw new ArgumentNullException(nameof(dllName));
            this.coverageFileName = coverageFileName ?? throw new ArgumentNullException(nameof(coverageFileName));

            if (interfaceWrappers != null && interfaceWrappers.Any())
            {
                this.interfaceWrappers = new Dictionary<string, WrapperInterface>(interfaceWrappers);
            }
            else
            {
                this.interfaceWrappers = new Dictionary<string, WrapperInterface>();
            }

            if (this.assembly == null)
            {
                throw new ArgumentException($"Failed to load assembly from {Path.Combine(resourceFolder, dllName)}");
            }

            this.dllName = this.assembly.ManifestModule.Name;
            this.coveredMethodInfoKeys = new HashSet<MethodCoverageInfoKey>();
            this.CoveredApiInfoKeys = new HashSet<MethodCoverageInfoKey>();
            this.AllApiInfoKeys = new HashSet<MethodCoverageInfoKey>();
            this.tempFilePath = $"{dllName}-CoverageInfoJson.json";
            this.extractorDirectory = this.GetExtractorDirectory();
        }

        /// <summary>
        /// Gets covered API function keys
        /// </summary>
        public HashSet<MethodCoverageInfoKey> CoveredApiInfoKeys { get; private set; }

        /// <summary>
        /// Gets all API function keys
        /// </summary>
        public HashSet<MethodCoverageInfoKey> AllApiInfoKeys { get; private set; }

        /// <summary>
        /// Start API coverage calculation against the specific dll and coverage file
        /// </summary>
        public void Calculate()
        {
            var start = this.sw.Elapsed;
            Console.WriteLine($"{this.dllName} - Start calculation.");

            this.CoveredApiInfoKeys.Clear();
            this.AllApiInfoKeys.Clear();
            this.InvokeParser();
            this.ReadParserResult();
            this.CalculateApiCoverage();
            if (this.interfaceWrappers.Any())
            {
                this.CalculateApiCoverageInWrappedInterface();
            }

            this.FinalizeResult();
            this.ClearTempFile();

            Console.WriteLine($"{this.dllName} - Finished in {(this.sw.Elapsed - start).TotalMilliseconds}ms. Result: {this.CoveredApiInfoKeys.Count} / {this.AllApiInfoKeys.Count}");
        }

        private static string RemoveInterfaceFromMethodName(MethodCoverageInfoKey key)
        {
            int interfaceIndex = key.MethodName.IndexOf(key.InterfaceName, StringComparison.Ordinal);

            // Remove interface name from method name for explicit implementation
            return interfaceIndex >= 0
                ? key.MethodName.Substring(interfaceIndex + key.InterfaceName.Length + 1)
                : key.MethodName;
        }

        private void FinalizeResult()
        {
            Console.WriteLine($"{this.dllName} - Finalizing coverage result.");
            HashSet<MethodCoverageInfoKey> total = new HashSet<MethodCoverageInfoKey>();
            HashSet<MethodCoverageInfoKey> covered = new HashSet<MethodCoverageInfoKey>();

            foreach (var key in this.AllApiInfoKeys)
            {
                MethodCoverageInfoKey newKey =
                    new MethodCoverageInfoKey(RemoveInterfaceFromMethodName(key), key.WrapperInterfaceName ?? key.InterfaceName, string.Empty, key.Parameters);
                total.Add(newKey);
            }

            foreach (var key in this.CoveredApiInfoKeys)
            {
                MethodCoverageInfoKey newKey =
                    new MethodCoverageInfoKey(RemoveInterfaceFromMethodName(key), key.WrapperInterfaceName ?? key.InterfaceName, string.Empty, key.Parameters);
                covered.Add(newKey);
            }

            this.AllApiInfoKeys = total;
            this.CoveredApiInfoKeys = covered;
            Console.WriteLine($"{this.dllName} - Finished coverage result finalization.");
        }

        private void CalculateApiCoverage()
        {
            Console.WriteLine($"{this.dllName} - Calculating API (direct implementation) coverage.");
            foreach (var module in this.assembly.GetModules())
            {
                foreach (var type in module.GetTypes())
                {
                    if (type.IsInterface)
                    {
                        continue;
                    }

                    foreach (var interfaceType in type.GetInterfaces())
                    {
                        this.CalculateApiCoverageForInterface(interfaceType, type);
                    }
                }
            }

            Console.WriteLine($"{this.dllName} - Finished calculation of API (direct implementation) coverage.");
        }

        private void CalculateApiCoverageForInterface(Type interfaceType, Type classType)
        {
            if (interfaceType.CustomAttributes.Any(a =>
                a.AttributeType != typeof(ServiceContractAttribute)))
            {
                return;
            }

            var map = classType.GetInterfaceMap(interfaceType);
            for (int i = 0; i < map.InterfaceMethods.Length; i++)
            {
                if (map.InterfaceMethods[i].CustomAttributes.Any(a =>
                        a.AttributeType == typeof(OperationContractAttribute))
                    && map.InterfaceMethods[i].CustomAttributes.All(a =>
                        a.AttributeType != typeof(ObsoleteAttribute)))
                {
                    this.AddApiCoverageInfo(map.TargetMethods[i], map.InterfaceMethods[i]);
                }
            }
        }

        private void CalculateApiCoverageInWrappedInterface()
        {
            Console.WriteLine($"{this.dllName} - Calculating API (indirect implementation) coverage.");

            // Include interface function covered in another interface component
            foreach (var module in this.assembly.GetModules())
            {
                foreach (var type in module.GetTypes())
                {
                    if (type.IsInterface)
                    {
                        continue;
                    }

                    foreach (var interfaceType in type.GetInterfaces())
                    {
                        this.CalculateApiCoverageInWrappedInterfaceForInterface(interfaceType, type);
                    }
                }
            }

            Console.WriteLine($"{this.dllName} - Finished calculation of API (indirect implementation) coverage.");
        }

        private void CalculateApiCoverageInWrappedInterfaceForInterface(Type interfaceType, Type classType)
        {
            if (interfaceType.FullName == null ||
                !this.interfaceWrappers.ContainsKey(interfaceType.FullName))
            {
                return;
            }

            Assembly wrapperInterfaceAssembly = Assembly.LoadFrom(Path.Combine(this.resourceFolder, this.interfaceWrappers[interfaceType.FullName].AssemblyName));

            if (wrapperInterfaceAssembly == null)
            {
                throw new ArgumentException($"Failed to load wrapper interface assembly from {Path.Combine(this.resourceFolder, this.interfaceWrappers[interfaceType.FullName].AssemblyName)}");
            }

            Type wrapperInterface =
                wrapperInterfaceAssembly.GetType(this.interfaceWrappers[interfaceType.FullName].InterfaceName, true, true);

            var apiMethodNames = wrapperInterface.GetMethods()
                .Where(m => m.CustomAttributes.Any(a =>
                                a.AttributeType == typeof(OperationContractAttribute))
                            && m.CustomAttributes.All(a => a.AttributeType != typeof(ObsoleteAttribute))).Select(a => a.Name)
                .ToList();

            var map = classType.GetInterfaceMap(interfaceType);
            for (int i = 0; i < map.InterfaceMethods.Length; i++)
            {
                if (apiMethodNames.Contains(map.InterfaceMethods[i].Name))
                {
                    this.AddApiCoverageInfo(map.TargetMethods[i], map.InterfaceMethods[i], wrapperInterface.FullName);
                }
            }
        }

        private void AddApiCoverageInfo(MethodInfo targetMethod, MethodInfo interfaceMethod, string wrapperInterfaceName = null)
        {
            var temp = new MethodCoverageInfoKey(
                targetMethod.Name,
                targetMethod.DeclaringType.Name,
                targetMethod.DeclaringType.Namespace,
                targetMethod.GetParameters().Select(this.GetTypeAlias).ToList());

            bool covered = this.coveredMethodInfoKeys.Contains(temp);

            temp.InterfaceName = interfaceMethod.DeclaringType.FullName;
            temp.WrapperInterfaceName = wrapperInterfaceName;

            if (covered)
            {
                this.CoveredApiInfoKeys.Add(temp);
            }

            this.AllApiInfoKeys.Add(temp);
        }

        private string GetTypeAlias(ParameterInfo info)
        {
            string output = string.Empty;
            var parameterType = info.ParameterType;
            if (info.IsOut && info.IsIn)
            {
                parameterType = parameterType.GetElementType();
                output = "ref ";
            }
            else if (info.IsOut)
            {
                parameterType = parameterType.GetElementType();
                output = "out ";
            }

            using (var provider = new CSharpCodeProvider())
            {
                var typeRef = new CodeTypeReference(parameterType);
                output += provider.GetTypeOutput(typeRef);
            }

            return output;
        }

        private void ReadParserResult()
        {
            Console.WriteLine($"{this.dllName} - Loading extraction result.");
            var methodCoverageInfos = new List<MethodCoverageInfo>();
            this.coveredMethodInfoKeys.Clear();

            using (FileStream stream = new FileStream(Path.Combine(this.extractorDirectory, this.tempFilePath), FileMode.Open))
            using (TextReader reader = new StreamReader(stream))
            {
                methodCoverageInfos.AddRange(JsonConvert.DeserializeObject<List<MethodCoverageInfo>>(reader.ReadToEnd()));
            }

            this.coveredMethodInfoKeys.UnionWith(methodCoverageInfos.Where(a => a.Value.Covered).Select(a => a.Key));
            Console.WriteLine($"{this.dllName} - Loaded extraction result.");
        }

        private void InvokeParser()
        {
            Console.WriteLine($"{this.dllName} - Extracting coverage info from: {this.coverageFileName}.");
            string extractorPath = Path.Combine(this.extractorDirectory, $@"{this.extractorName}.exe");
            using Process extractor = new Process
            {
                StartInfo =
                {
                    FileName = extractorPath,
                    Arguments = $"{this.coverageFileName} {this.dllName}",
                },
            };
            extractor.Start();

            if (!extractor.WaitForExit(30000))
            {
                extractor.Kill();
                throw new TimeoutException($"Extractor for {this.dllName} timeout after 30 seconds.");
            }

            Console.WriteLine($"{this.dllName} - Finished coverage info extraction.");
        }

        private string GetExtractorDirectory()
        {
            var parentDirectory = new FileInfo(Assembly.GetEntryAssembly().Location).Directory.Parent;
            var extractorDirectory = parentDirectory.GetDirectories()
                .FirstOrDefault(directory => string.Equals(directory.Name, this.extractorName, StringComparison.Ordinal));
            if (extractorDirectory == null)
            {
                throw new DirectoryNotFoundException($"Cannot find {this.extractorName} folder under {parentDirectory}");
            }

            return extractorDirectory.FullName;
        }

        private void ClearTempFile()
        {
            File.Delete(Path.Combine(this.extractorDirectory, this.tempFilePath));
        }
    }
}
