<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <RuntimeFrameworkVersion>$(DotNetCoreVersion)</RuntimeFrameworkVersion>
    <IsServiceFabricServiceProject>True</IsServiceFabricServiceProject>
    <OutputType>Exe</OutputType>
    <RootNamespace>Microsoft.Azure.Networking.Infrastructure.RingMaster.ConnectionStressService</RootNamespace>
    <AssemblyName>Microsoft.RingMaster.Test.ConnectionStressService</AssemblyName>
    <CoverageDisabled>true</CoverageDisabled>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition="'$(QBUILD)' != ''">
    <OutputPath>$(OutputRoot)RingMasterTestApplication-Pkg\RingMasterTestApplication\$(MSBuildProjectName)\Code</OutputPath>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Cloud.InstrumentationFramework.NetStd" Condition="'$(OSSBUILD)' == ''" />
    <PackageReference Include="Bond.CSharp" />
    <PackageReference Include="Microsoft.ServiceFabric" />
    <PackageReference Include="Microsoft.ServiceFabric.Data" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Extensions" />
    <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SRCROOT)\Backend\HelperTypes\src\HelperTypes.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\Common\Common.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\RingMasterCommunicationProtocol\RingMasterCommunicationProtocol.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\Instrumentation\Instrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterClient\src\RingMasterClient.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterCommon\src\RingMasterCommon.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\SecureTransport\src\SecureTransport.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\IfxInstrumentation\IfxInstrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\ServiceFabric\src\ServiceFabric.csproj" />
    <ProjectReference Include="$(SRCROOT)\Tests\PerformanceTestCases\PerformanceTestCases.csproj" />
    <ProjectReference Include="..\..\TestHelpers\TestHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <QCustomInput Include="PackageRoot\ServiceManifest.xml" />
  </ItemGroup>

</Project>
