// <copyright file="RingMasterEventSourceKeywords.cs" company="Microsoft Corporation">
//   Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>

namespace Microsoft.Azure.Networking.Infrastructure.RingMaster.Backend
{
    using System.Diagnostics.Tracing;

    /// <summary>
    /// Contains a set of keywords for filtering events generated by <see cref="RingMasterEventSource"/>.
    /// </summary>
    public static class RingMasterEventSourceKeywords
    {
        /// <summary>
        /// Returns the <see cref="EventKeywords"/> for tracing all the messages but <see cref="RingMasterEventSource.ProcessMessageSucceeded(ulong,ulong,long,int,string,long,string)"/>.
        /// </summary>
        public static EventKeywords ExcludeProcessMessage => EventKeywords.All & (~RingMasterEventSource.Keywords.ProcessMessage);
    }
}
