<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <RootNamespace>Microsoft.Vega.Test</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Backend\Core\src\RingMasterBackendCore.csproj" />
    <ProjectReference Include="..\..\Common\CommunicationProtocol\src\RingMasterCommunicationProtocol\RingMasterCommunicationProtocol.csproj" />
    <ProjectReference Include="..\..\Common\RingMasterCommon\src\RingMasterCommon.csproj" />
    <ProjectReference Include="..\..\Common\SecureTransport\src\SecureTransport.csproj" />
    <ProjectReference Include="..\..\Persistence\InMemory\src\InMemoryPersistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" />
  </ItemGroup>

  <Import Project="$(StyleCopProps)" />
</Project>
