<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <CoverageDisabled>true</CoverageDisabled>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SRCROOT)\Infrastructure\LogFileEventTracing\LogFileEventTracing.csproj" />
  </ItemGroup>

  <Import Project="$(StyleCopProps)" />
</Project>
