// <copyright file="CoverageInfoExtractor.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>

namespace CoverageInfoExtractor
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.IO;
    using System.Linq;
    using System.Reflection;

    using global::CoverageInfoExtractor.MethodCoverageInfoModel;

    using Microsoft.VisualStudio.Coverage.Analysis;
    using Newtonsoft.Json;

    /// <summary>
    /// CoverageInfoExtractor, extract method coverage info from coverage file generated by VS and store it to JSON for calculator to read
    /// </summary>
    [ExcludeFromCodeCoverage]
    internal class CoverageInfoExtractor
    {
        private readonly string coverageFilePath;
        private readonly string dllName;
        private readonly List<MethodCoverageInfo> coverageInfo = new List<MethodCoverageInfo>();

        /// <summary>
        /// Initializes a new instance of the <see cref="CoverageInfoExtractor"/> class
        /// </summary>
        /// <param name="coverageFilePath">Absolute path of the coverage file</param>
        /// <param name="dllName">Assembly name for this coverage</param>
        internal CoverageInfoExtractor(string coverageFilePath, string dllName)
        {
            this.coverageFilePath = coverageFilePath ?? throw new ArgumentNullException(nameof(coverageFilePath));
            this.dllName = dllName ?? throw new ArgumentNullException(nameof(dllName));
        }

        /// <summary>
        /// Extract method coverage info from .coverage file and store it to JSON for calculator to read
        /// </summary>
        internal void Extract()
        {
            this.GetMethodCoverageInfoFromCoverageFile();
            this.StoreToLocal();
        }

        private void GetMethodCoverageInfoFromCoverageFile()
        {
            using (CoverageInfo info = CoverageInfo.CreateFromFile(this.coverageFilePath))
            {
                CoverageDS data = info.BuildDataSet();
                foreach (var method in data.Method)
                {
                    this.coverageInfo.Add(new MethodCoverageInfo(
                        this.CreateCoverageInfoKey(method),
                        new MethodCoverageInfoValue(method.BlocksCovered, method.BlocksNotCovered)));
                }
            }
        }

        private void StoreToLocal()
        {
            string tempFileName =
                Path.Combine(
                    new FileInfo(Assembly.GetEntryAssembly().Location).DirectoryName ?? throw new InvalidOperationException(),
                    $"{this.dllName}-CoverageInfoJson.json");
            using (FileStream stream = new FileStream(tempFileName, FileMode.Create))
            using (TextWriter writer = new StreamWriter(stream))
            {
                writer.Write(JsonConvert.SerializeObject(this.coverageInfo));
                writer.Flush();
            }
        }

        private MethodCoverageInfoKey CreateCoverageInfoKey(CoverageDSPriv.MethodRow method)
        {
            int methodNameEnd = method.MethodName.IndexOf("(", StringComparison.Ordinal);
            int classNameEnd = method.MethodKeyName.IndexOf('!');
            int classNameStart = this.dllName.Length + 36; // length of a Guid
            int parameterLength = Math.Max(method.MethodName.IndexOf(")", methodNameEnd, StringComparison.Ordinal) - methodNameEnd - 1, 0);

            List<string> parameters =
                parameterLength > 0
                    ? method.MethodName.Substring(methodNameEnd + 1, parameterLength).Split(',').Select(a => a.Trim()).ToList()
                    : new List<string>();

            var key = new MethodCoverageInfoKey(
                method.MethodName.Substring(0, methodNameEnd),
                method.MethodKeyName.Substring(classNameStart, classNameEnd - classNameStart),
                string.Empty,
                parameters);

            return key;
        }
    }
}
