// <copyright file="Program.cs" company="Microsoft Corporation">
// Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>

namespace CoverageInfoExtractor
{
    using System;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// CoverageInfoExtractor, extract method coverage info from coverage file generated by VS and store it to JSON for calculator to read
    /// This is separate to another executable because the VS dependency is x86 only
    /// </summary>
    [ExcludeFromCodeCoverage]
    public static class Program
    {
        /// <summary>
        /// Extract method coverage info from .coverage file and store it to JSON for calculator to read
        /// </summary>
        /// <param name="args">0: Absolute path for coverage file; 1: Assembly name of the coverage file</param>
        public static void Main(string[] args)
        {
            if (args == null)
            {
                throw new ArgumentNullException(nameof(args));
            }

#pragma warning disable CA1303 //  Retrieve the following string(s) from a resource table instead
            if (args.Length != 2)
            {
                throw new ArgumentException($"CoverageInfoExtractor expects 2 parameters");
            }
#pragma warning restore

            string coverageFileName = args[0];
            string dllName = args[1];
            CoverageInfoExtractor extractor = new CoverageInfoExtractor(coverageFileName, dllName);
            extractor.Extract();
        }
    }
}
