<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>Microsoft.Vega.Test</RootNamespace>
    <AssemblyName>VegaUpgradeTest</AssemblyName>
    <EnableQTest>false</EnableQTest>
    <CoverageDisabled>true</CoverageDisabled>
    <PublishDir>$(OutputPath)</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.ServiceFabric" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SRCROOT)\Backend\HelperTypes\src\HelperTypes.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\Common\Common.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\CommunicationProtocol\src\RingMasterCommunicationProtocol\RingMasterCommunicationProtocol.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\Instrumentation\Instrumentation.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterClient\src\RingMasterClient.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\RingMasterCommon\src\RingMasterCommon.csproj" />
    <ProjectReference Include="$(SRCROOT)\Common\SecureTransport\src\SecureTransport.csproj" />
    <ProjectReference Include="$(SRCROOT)\Infrastructure\IfxInstrumentation\IfxInstrumentation.csproj" />
    <ProjectReference Include="..\TestHelpers\TestHelpers.csproj" />
  </ItemGroup>

  <Target Name="dummy" AfterTargets="Build" DependsOnTargets="Publish" Condition="'$(BuildingInsideVisualStudio)' == ''" />

  <Import Project="$(StyleCopProps)" />
</Project>
