<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\NuprojCommon.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NoBuild>true</NoBuild>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageId>VegaDistributedTest$(NamePostfix)</PackageId>
    <PackageVersion>$(BuildNumber)</PackageVersion>
    <Authors>vegab@microsoft.com</Authors>
    <Title>Vega Distributed Test Framework</Title>
    <Description>Vega distributed test framework</Description>
    <Copyright>Copyright (c) Microsoft Corporation</Copyright>
    <PackageProjectUrl>https://b</PackageProjectUrl>
    <PackageTags>RingMaster;VegaDistributedTestFramework</PackageTags>
    <RepositoryUrl>http://aka.ms/vega</RepositoryUrl>
    <RepositoryBranch>$(GitBranchName)</RepositoryBranch>
    <RepositoryCommit>$(GitCommitHash)</RepositoryCommit>
    <PackageOutputPath>$(OutputRoot)\packages</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SRCROOT)\Tests\VegaDistributedTest\VegaDistributedTestContracts\VegaDistributedTestContracts.csproj" PrivateAssets="All" />
    <ProjectReference Include="$(SRCROOT)\Tests\VegaDistributedTest\VegaDistributedTestFramework\VegaDistributedTestFramework.csproj" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <libs Include="$(OutputPath)\VegaDistributedTestContracts.dll" />
    <libs Include="$(OutputPath)\VegaDistributedTestContracts.pdb" />
    <libs Include="$(OutputPath)\VegaDistributedTestFramework.dll" />
    <libs Include="$(OutputPath)\VegaDistributedTestFramework.pdb" />
	
    <Content Include="@(libs)">
      <PackagePath>lib\netstandard2.0</PackagePath>
    </Content>
  </ItemGroup>
</Project>
