<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <RootNamespace>Microsoft.Vega.Test.Helpers</RootNamespace>
    <AssemblyName>TestHelpers</AssemblyName>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <CoverageDisabled>true</CoverageDisabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Instrumentation\Instrumentation.csproj" />
    <ProjectReference Include="..\..\Common\RingMasterClient\src\RingMasterClient.csproj" />
    <ProjectReference Include="..\..\Common\RingMasterCommon\src\RingMasterCommon.csproj" />
    <ProjectReference Include="..\..\Infrastructure\IfxInstrumentation\IfxInstrumentation.csproj" />
    <ProjectReference Include="..\..\Infrastructure\LogFileEventTracing\LogFileEventTracing.csproj" />
  </ItemGroup>

  <Import Project="$(StyleCopProps)" />
</Project>
