<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreAppVer)</TargetFramework>
    <RootNamespace>Microsoft.Vega.VegaLogAnalyzer</RootNamespace>
    <AssemblyName>Microsoft.Vega.VegaLogAnalyzer</AssemblyName>
    <CoverageDisabled>true</CoverageDisabled>
  </PropertyGroup>

  <Import Project="$(StyleCopProps)" />

  <ItemGroup>
    <None Update="ValidPathRegex.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
